server:
  port: 8081
  
spring:
  h2:
    console:
      enabled: true
      path: /h2-console 

#  datasource:
#    url: jdbc:h2:~/test;
#    driverClassName: org.h2.Driver
#    username: sa
#    password:

  datasource:
    url: jdbc:mysql://localhost:3306/zzami_alarm
    driver-class-name: com.mysql.cj.jdbc.Driver 
    username: root
    password: root
    
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      use-new-id-generator-mappings: false
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    '[org.springframework.orm]': DEBUG
    '[org.springframework.transaction]': TRACE
    '[org.hibernate.sql]': DEBUG
    '[org.hibernate.type]': TRACE  
 